package xyz.whatsyouss.frosty.utility.commission.pathfinder;

import net.minecraft.core.BlockPos;
import net.minecraft.world.level.block.state.BlockState;

public enum Moves {
    TRAVERSE_NORTH(0,-1,0), TRAVERSE_SOUTH(0,1,0), TRAVERSE_EAST(1,0,0), TRAVERSE_WEST(-1,0,0),
    ASCEND_NORTH(0,-1,1), ASCEND_SOUTH(0,1,1), ASCEND_EAST(1,0,1), ASCEND_WEST(-1,0,1),
    DESCEND_NORTH(0,-1,-1), DESCEND_SOUTH(0,1,-1), DESCEND_EAST(1,0,-1), DESCEND_WEST(-1,0,-1),
    DIAGONAL_NORTHEAST(1,-1,2), DIAGONAL_NORTHWEST(-1,-1,2), DIAGONAL_SOUTHEAST(1,1,2), DIAGONAL_SOUTHWEST(-1,1,2);
    private final int dx,dz,type;
    Moves(int dx,int dz,int type) { this.dx=dx; this.dz=dz; this.type=type; }
    public void calculate(CalculationContext ctx,int x,int y,int z,MovementResult result) { int tx=x+dx,tz=z+dz; result.set(tx,y+(type==1?1:type==-1?-1:0),tz); if(type==0) traverse(ctx,x,y,z,tx,tz,result); else if(type==1) ascend(ctx,x,y,z,tx,tz,result); else if(type==-1) descend(ctx,x,y,z,tx,tz,result); else diagonal(ctx,x,y,z,tx,tz,result); }
    private static void traverse(CalculationContext c,int x,int y,int z,int tx,int tz,MovementResult r) { if(!MovementHelper.canStandOn(c.bsa,tx,y,tz)||!MovementHelper.canWalkThrough(c.bsa,tx,y+1,tz,c.get(tx,y+1,tz))||!MovementHelper.canWalkThrough(c.bsa,tx,y+2,tz)) return; BlockState up=c.get(tx,y+1,tz), srcUp=c.get(x,y+1,z); if(MovementHelper.isLadder(up)&&!MovementHelper.canWalkIntoLadder(up,tx-x,tz-z)||MovementHelper.isLadder(srcUp)&&!MovementHelper.canWalkIntoLadder(srcUp,x-tx,z-tz)) return; double diff=MovementHelper.collisionMaxY(c.get(tx,y,tz),c.world,new BlockPos(tx,y,tz))-MovementHelper.collisionMaxY(c.get(x,y,z),c.world,new BlockPos(x,y,z)); r.cost=diff<=.5?c.cost.ONE_BLOCK_SPRINT_COST:diff<=1?c.cost.JUMP_ONE_BLOCK_COST:c.cost.INF_COST; }
    private static void ascend(CalculationContext c,int x,int y,int z,int tx,int tz,MovementResult r) { BlockState dest=c.get(tx,y+1,tz); if(!MovementHelper.canStandOn(c.bsa,tx,y+1,tz,dest)||!MovementHelper.canWalkThrough(c.bsa,tx,y+3,tz)||!MovementHelper.canWalkThrough(c.bsa,tx,y+2,tz)||!MovementHelper.canWalkThrough(c.bsa,x,y+3,z))return; BlockState src=c.get(x,y,z); if(MovementHelper.isLadder(src)||MovementHelper.isLadder(dest)&&!MovementHelper.canWalkIntoLadder(dest,tx-x,tz-z))return; double diff=MovementHelper.collisionMaxY(dest,c.world,new BlockPos(tx,y+1,tz))-MovementHelper.collisionMaxY(src,c.world,new BlockPos(x,y,z));r.cost=diff<=.5?c.cost.ONE_BLOCK_SPRINT_COST:diff<=1.125?c.cost.JUMP_ONE_BLOCK_COST:c.cost.INF_COST; }
    private static void descend(CalculationContext c,int x,int y,int z,int tx,int tz,MovementResult r) { BlockState up=c.get(tx,y,tz),src=c.get(x,y,z),dest=c.get(tx,y-1,tz);if(!MovementHelper.canWalkThrough(c.bsa,tx,y+2,tz)||!MovementHelper.canWalkThrough(c.bsa,tx,y+1,tz)||!MovementHelper.canWalkThrough(c.bsa,tx,y,tz,up)||MovementHelper.isLadder(src)||MovementHelper.isLadder(up))return;if(!MovementHelper.canStandOn(c.bsa,tx,y-1,tz,dest)||MovementHelper.isLadder(dest)){freeFall(c,y,tx,tz,dest,r);return;}double diff=MovementHelper.collisionMaxY(src,c.world,new BlockPos(x,y,z))-MovementHelper.collisionMaxY(dest,c.world,new BlockPos(tx,y-1,tz));r.cost=diff<=.5?c.cost.ONE_BLOCK_WALK_COST:diff<=1.125?c.cost.WALK_OFF_ONE_BLOCK_COST*c.cost.SPRINT_MULTIPLIER+c.cost.N_BLOCK_FALL_COST[1]:c.cost.INF_COST; }
    private static void freeFall(CalculationContext c,int y,int tx,int tz,BlockState first,MovementResult r){if(!MovementHelper.canWalkThrough(c.bsa,tx,y-1,tz,first))return;int effective=y;double extra=0;for(int fell=2;;fell++){int ny=y-fell;if(ny<0)return;BlockState onto=c.get(tx,ny,tz);int unprotected=fell-(y-effective);double total=c.cost.WALK_OFF_ONE_BLOCK_COST+c.cost.N_BLOCK_FALL_COST[unprotected]+extra+unprotected*2;if(!MovementHelper.canStandOn(c.bsa,tx,ny,tz,onto)){if(MovementHelper.isWotah(onto)){if(MovementHelper.canStandOn(c.bsa,tx,ny-1,tz)){r.y=ny-1;r.cost=total;}return;}if(!MovementHelper.canWalkThrough(c.bsa,tx,ny,tz,onto))return;continue;}if(unprotected<=11&&MovementHelper.isLadder(onto)){extra+=c.cost.N_BLOCK_FALL_COST[unprotected-1]+c.cost.ONE_DOWN_LADDER_COST;effective=ny;continue;}if(fell<=c.maxFallHeight){r.y=ny;r.cost=total;}return;}}
    private static void diagonal(CalculationContext c,int x,int y,int z,int tx,int tz,MovementResult r){if(!MovementHelper.canWalkThrough(c.bsa,tx,y+2,tz))return;boolean up=false,down=false;BlockState src=c.get(x,y,z),dest=c.get(tx,y,tz);if(!MovementHelper.canWalkThrough(c.bsa,tx,y+1,tz)){up=true;if(!MovementHelper.canWalkThrough(c.bsa,x,y+3,z)||!MovementHelper.canStandOn(c.bsa,tx,y+1,tz)||!MovementHelper.canWalkThrough(c.bsa,tx,y+2,tz))return;dest=c.get(tx,y+1,tz);r.y=y+1;}else if(!MovementHelper.canStandOn(c.bsa,tx,y,tz,dest)){down=true;if(!MovementHelper.canStandOn(c.bsa,tx,y-1,tz)||!MovementHelper.canWalkThrough(c.bsa,tx,y,tz))return;dest=c.get(tx,y-1,tz);r.y=y-1;}if(MovementHelper.isLadder(src))return;double cost=MovementHelper.isWotah(c.get(x,y+1,z))?c.cost.ONE_BLOCK_WALK_IN_WATER_COST*Math.sqrt(2):c.cost.ONE_BLOCK_WALK_COST*c.cost.SPRINT_MULTIPLIER;if(up&&MovementHelper.isWotah(c.get(x,y+1,z)))return;if(!MovementHelper.canWalkThrough(c.bsa,x,y+3,tz)||!MovementHelper.canWalkThrough(c.bsa,x,y+2,tz)||!MovementHelper.canWalkThrough(c.bsa,x,y+1,tz)||!MovementHelper.canWalkThrough(c.bsa,tx,y+3,z)||!MovementHelper.canWalkThrough(c.bsa,tx,y+2,z)||!MovementHelper.canWalkThrough(c.bsa,tx,y+1,z))return;if(!up&&!down){r.cost=cost*Math.sqrt(2);return;}double srcY=MovementHelper.collisionMaxY(src,c.world,new BlockPos(x,y,z)),destY=MovementHelper.collisionMaxY(dest,c.world,new BlockPos(tx,y+(up?1:-1),tz));double diff=up?destY-srcY:srcY-destY;r.cost=diff<=.5?cost*Math.sqrt(2):up&&diff<=1.125?cost*Math.sqrt(2)+c.cost.JUMP_ONE_BLOCK_COST:down&&diff<=1?c.cost.N_BLOCK_FALL_COST[1]+cost*Math.sqrt(2):c.cost.INF_COST;}
}
